### ISSUE TITLE
你好，请问mapa论文的supplementary material在哪呢，找了一圈没找到呀

### ISSUE THREAD

**Issue by changfali** [zhanghe3z/MaPa#1]
方便发一下链接吗，想具体了解一下论文中RGB图片生成albedo的过程
![img_v3_02f1_89ee6466-a457-4ca4-b155-e81422ab8dag](https://github.com/user-attachments/assets/9a286266-cdb2-427b-af37-1868aee13213)
![img_v3_02f1_e4fa4802-7456-426a-aa6f-3e7b0aea32fg](https://github.com/user-attachments/assets/64afb74f-c937-4895-8808-4bdb1b8f6a87)

**Comment by zhanghe3z** [comment]
你的邮箱是多少我发你邮箱
